### ISSUE TITLE
Appointment view on CDS Sandbox?

### ISSUE THREAD

**Issue by thuann-vn** [cerner/cds-services-tutorial#21]
Hello, I want to test the appointment view hook, how could I do that?

**Comment by dennispatterson** [comment]
Hi Thua!  I cross-posted your question to the CDS Hooks google group with a comment on where to get started.  You can share more about your use-cases and needs there.  https://groups.google.com/g/cds-hooks/c/F0G6AeWYHMk/m/uI7fTnAzAAAJ
